article/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "article"

urlpatterns = [
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("addarticle/", views.addarticle, name = "addarticle"),
    path("article/<int:id>", views.detail, name = "detail"),
    path("update/<int:id>", views.updatearticle, name = "update"),
    path("delete/<int:id>", views.deletearticle, name = "delete"),
    path("comment/<int:id>", views.addcomment, name = "comment"),
    #burada linkin sanki index gibi boş olmasının sebebi blog urls içerisinde articles ı dahil etmemiş olmamız. buradaki boşluk domin/articles şeklinde dolduruluyor olacak.
    path("", views.articles, name = "articles"),
]

blog/urls.py
from django.contrib import admin
#211. derste moduler url kullanımı için include import edildi
from django.urls import path, include
#204. derste index sayfasının hazırlanması işlemleri içerisinde eklendi. index i render eden fonksiyon böylece buraya import edilmiş oldu.
from article import views
# settings ve static importları sadece geliştirme sürecinde olmalılar
#settings ve static dosya yükleme işlemi için dahil edildi.
from django.conf import settings
from django.conf.urls.static import static
""" from django.conf import settings
from django.conf.urls.static import static """

urlpatterns = [
    path('admin/', admin.site.urls),
    #anasayfa/landing page için tırnaklar içerisi boş bırakıldı, eğer / girişmiş olsaydı Django hata verecekti.
    # Flask'taki url_for işlemine benzer bir işlem yapmak için burada name attr. oluşturarak bu işlemi yapabiliyoruz.
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    #dinamik id yapısını deneme amaçlı oluşturduğumuz sayfa yolu
    path('detail/<int:id>', views.detail, name = "detail"),
    #211. derste modüler url yapısına örnek olarak eklendi.
    path('articles/',include("article.urls")),
    #user/register, user/login, user/logout url lerini bağlayan path
    path("user/", include("user.urls") ),
] 

#Dosya yüklerken MEDIA_URL ve MEDIA_ROOT a erişim için
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.register, name = "register"),
    path("login/", views.loginuser, name = "login"),
    path("logout/", views.logoutuser, name = "logout"),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">CE Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:articles' %}"><strong>Blog Yazıları</strong> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'about' %}"><strong>Hakkımda</strong><span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <!-- Henüz session["logged_in"] fonksiyon yapısı hazır olmadığı için yorumda -->
      {% if request.user.is_authenticated %}
        <li class="nav-item active"><a href="{% url 'article:dashboard' %}" class="nav-link"><strong>Kontrol Paneli</strong></a>
        </li>
        <li class="nav-item active"><a href="{% url 'user:logout' %}" class="nav-link"><strong>Çıkış</strong></a>
        </li>
      {% else %}
        <li class="nav-item active"><a href="{% url 'user:login' %}" class="nav-link"><strong>Giriş</strong></a>
        </li>
        <li class="nav-item active"><a href="{% url 'user:register' %}" class="nav-link"><strong>Kayıt Ol</strong></a>
          </li>
      {% endif %}    
    </ul>

    <!-- Dropdown menu yapısı daha sonra lazım olabileceği için yorumda -->

     {% comment %}  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> {% endcomment %}
  </div>
</nav>

templates/includes/posttemplate.html
    <!-- https://startbootstrap.github.io/startbootstrap-blog-post/ adresinden alındı -->
    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->