article/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "article"

urlpatterns = [
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("addarticle/", views.addarticle, name = "addarticle"),
    path("article/<int:id>", views.detail, name = "detail"),
    path("update/<int:id>", views.updatearticle, name = "update"),
    path("delete/<int:id>", views.deletearticle, name = "delete"),
    path("comment/<int:id>", views.addcomment, name = "comment"),
    #burada linkin sanki index gibi boş olmasının sebebi blog urls içerisinde articles ı dahil etmemiş olmamız. buradaki boşluk domin/articles şeklinde dolduruluyor olacak.
    path("", views.articles, name = "articles"),
]

blog/urls.py
from django.contrib import admin
#211. derste moduler url kullanımı için include import edildi
from django.urls import path, include
#204. derste index sayfasının hazırlanması işlemleri içerisinde eklendi. index i render eden fonksiyon böylece buraya import edilmiş oldu.
from article import views
# settings ve static importları sadece geliştirme sürecinde olmalılar
#settings ve static dosya yükleme işlemi için dahil edildi.
from django.conf import settings
from django.conf.urls.static import static
""" from django.conf import settings
from django.conf.urls.static import static """

urlpatterns = [
    path('admin/', admin.site.urls),
    #anasayfa/landing page için tırnaklar içerisi boş bırakıldı, eğer / girişmiş olsaydı Django hata verecekti.
    # Flask'taki url_for işlemine benzer bir işlem yapmak için burada name attr. oluşturarak bu işlemi yapabiliyoruz.
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    #dinamik id yapısını deneme amaçlı oluşturduğumuz sayfa yolu
    path('detail/<int:id>', views.detail, name = "detail"),
    #211. derste modüler url yapısına örnek olarak eklendi.
    path('articles/',include("article.urls")),
    #user/register, user/login, user/logout url lerini bağlayan path
    path("user/", include("user.urls") ),
] 

#Dosya yüklerken MEDIA_URL ve MEDIA_ROOT a erişim için
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Article(models.Model):
    """
    Veritabanında blog yazılarının satırlarını ve hücrelerini tanımlayan model sınıfı
    """
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name= "Yazar")
    title = models.CharField(max_length=50, verbose_name= "Başlık")
    #226. derste ckeditor eklendiği için yoruma alındı
    """ content = models.TextField(verbose_name= "İçerik") """
    #CkEditor alanı
    content = RichTextField(verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name= "Oluşturma Tarihi")
    article_image = models.FileField(blank=True, null=True, verbose_name="Dosya Yükle")

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    Article modelinden oluşturulmuş blog yazılarına bağlanan kullanıcı yorumları modeli
    """
    # foreign key yardımı ile yorumları article lara bağlıyoruz
    # on_delete = models.CASCADE ile de article silinirse yorumların da otomatik olarak silinmesi sağlıyoruz.
    # related_name özelliğini ise article ların ilerde "yorumlarını" alabilmek için article.comments ile yorum tablosunu almayı sağladık
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Makale", related_name = "comments")
    # yorumu yazan kişi isim bilgileri
    comment_author = models.CharField(max_length = 50, verbose_name = "İsminiz:")
    #yorum email alanı CharField ile hazırlandı ancak widget a models.EmailInput özelliği ve placeholder eklendi
    comment_email = models.EmailField(max_length = 40, verbose_name = "Eposta Adresiniz:")
    comment_content = models.TextField(max_length = 1000, verbose_name = "Yorumunuz:")
    # yorumu gönderme tarihini otomatik olarak eklemesi için auto_now_add=True
    comment_date = models.DateTimeField(auto_now_add = True)
    # alanlar oluşturulduktan sonra admin paneline bu modeli kayıt ediyoruz article/admin.py
    def __str__(self):
        return self.comment_content

article/forms.py
from django import forms
#Django dokümanda anlatıldıkğ gibi daha önceden hazırladığımız Article Model sınıfını buraya dahil ediyoruz
from .models import Article

#forms.Formdan farklı olarak Django doc tan models den form hazırlama yöntemi kullanıldı
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        #daha önce oluşturduğumuz Article Modelinde author, title, content ve created_alanlarını oluşturmuştuk ancak bu sayfada sadece input alanı olarak  title/content kullanacağız
        # 227. derste dosya yükleme alanı için "article_image" eklendi
        fields = ["title", "content", "article_image"]

article/views.py
#221. derste fonksiyona redirect import edildi ve kullanıldı
from django.shortcuts import render, HttpResponse,redirect, reverse, get_object_or_404
#HttpResponse 204. derte eklendi. index fonk. hazırlanırken işlemin daha kolay anlaşılabilmesi için tercih edildi. Sayfaya direk fonksiyonu içerisinde yazı gönderebiliyoruz.
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
#221. derste fonksiyona messeges özelliği eklemek için import edildi
from django.contrib import messages
#223. derste veritabanından veri alma işlemi için import edildi
from .models import Article, Comment
from user import views
# Create your views here.
#request değişkeni sayfaya yapılan isteklerin Django tarafından yakalanarak oluşturuluyor.Her view fonksiyonunda mutlaka bulunmalı ve ilk parametre olmalı. GET ya da POST olduğunu bu değişken aracılığı ile anlayacağız.

#anasayfa fonksiyonu
def index(request):
    """Anasayfa yönlendirmesini yapan fonk."""
    # Sayfaya http responce yani içerisindeki kelime yazdırma işlemi için kullanıldı ve kaldırıldık.
    #return HttpResponse("Peh!")
    return render(request, "index.html")

#Hakkımda sayfasının fonksiyonu
def about(request):
    """Hakkımda sayfasının urlsini döndüren fonksiyon"""
    return render(request, "about.html")

""" #deneme amaçlı oluşturulan dinamik id fonksiyonu
def detail(request, id):
    #Veritabanında id int olarak kayıtlı. Sayfaya gönderebilmek için str'ye çevirmek gerekiyor yoksa Django sayfada int / str hatası veriyor.
    return HttpResponse("Deneme: " + str(id)) """

#dashboard fonksiyonu
@login_required(login_url="user:login")
def dashboard(request):
    #online kullanıcının yazılarını veritabanında almamız gerekiyor. Veritabanından sözlük yapısında bilgileri alıyoruz.
    articles = Article.objects.filter(author = request.user).order_by("-created_date")
    context = {"articles": articles,}
    return render(request, "dashboard.html", context)

#blog yazı yazma ekran fonksiyonu
@login_required(login_url="user:login")
def addarticle(request):
    #227. derste dosya yükleme işlemini sağlamak için request.FILES or None eklendi
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        #Bu form model ile ilişkili bir form olduğu için sadece kayıt işlemi yapmak yeterli ancak formumuzda user id olmadığı için yazı kaydet denildiğinde Django hata dönüyor. O yüzden öncelikle veritabanına yazma işlemini beklemeye almamız gerekiyor bu yüzden commit=False ekliyoruz ve form.save() i bir değişkene aktarıyoruz
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Yazınız yayınlandı!")
        return redirect("article:dashboard")
    context = {"form": form}
    return render(request, "addarticle.html", context)

#makalere dinamik url ile yönlendiren fonksiyon
#238. dersle sayfada yorumları gösterir hala getirildi
def detail(request, id):
    #224. derste 404 özelliği için yoruma alındı
    """ article = Article.objects.filter(id = id).first() """
    article = get_object_or_404(Article, id = id)
    #context 238. de yoruma alındı çünkü comments de eklendi
    #context = {"article": article}
    #Comment modelini oluşturduğumuzda related_name olarak comments ismini kullanmıştık burada article değişkenine ekleyerek o makalenin ilişkili olduğu yorumların hepsini alabiliyoruz.
    comments = article.comments.all().order_by("-comment_date")
    #context e comments eklendi
    context = {
        "article": article,
        "comments": comments,
    }
    return render(request, "detail.html", context)

#aktif kullanıcının kendine ait yazıları güncelleye fonksiyon
@login_required(login_url="user:login")
def updatearticle(request, id):
    article = get_object_or_404(Article, id = id)
        #article nesnesi içerisinde tüm bilgiler instance parametresine aktarılıyor ve böylece modelin gerekli alanları doldurularak form nesnesine işleniyor
    if request.user.id == article.author_id:
        form = ArticleForm(request.POST or None, request.FILES or None, instance= article)
        if form.is_valid():
            article = form.save(commit = False)
            article.author = request.user
            article.save()
            messages.success(request, "Yazınız güncellendi.")
            return redirect("article:dashboard")
        context = {"form": form}
        return render(request, "update.html", context)
    messages.info(request, "Bu yazı size ait değil!")
    return redirect("index")

#aktif kullanıcının kendine ait yazıları silen fonksiyon
@login_required(login_url="user:login")
def deletearticle(request, id):
    article = get_object_or_404(Article, id = id)
    if request.user.id == article.author_id:
        article.delete()
        messages.success(request, "Yazınız silindi.")
        return redirect("article:dashboard")
    messages.info(request, "Bu yazı size ait değil!")
    return redirect("index")

#Blog yazıları sayfasının fonksiyonu
def articles(request):
    #234. derste arama işlemi için keyword değişkeni ve if bloğu eklendi
    #request.GET "get" requesti yakalarken .get ise bunun içindeki name alanının içeriğini almak için kullanıldı
    keyword = request.GET.get("keyword")
    #eğer arama işlemi yapılmazsa ya da boş dönerse sorgusu hazırlandı
    if keyword:
        #__contains ile arama işleminin yapılacağı alanın içeriği karşılaştırılarak veritabanından eşleşen yazılar alındı
        articles = Article.objects.filter(title__contains = keyword)
        #yazılar context e bağlantı
        context = {"articles": articles}
        return render(request, "articles.html", context)
    #içinde sözlük bulanan liste nesnesi
    articles = Article.objects.all().order_by("-created_date")
    context = {"articles": articles,}
    return render(request, "articles.html", context)

#yorum gönderme ve veritabanına yazma fonksiyonu
def addcomment(request, id):
    article = get_object_or_404(Article, id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_email = request.POST.get("comment_email")
        comment_content = request.POST.get("comment_content")
        new_comment = Comment(comment_author = comment_author, comment_content = comment_content, comment_email = comment_email)
        new_comment.article = article
        new_comment.save()
    # buradaki redirect link yazımı çok iyi bir örnek değil.    
    #return redirect("/articles/article/" + str(id))
    #best-practise için reverse() fonksiyonu
    return redirect(reverse("article:detail", kwargs={"id": id}))

templates/about.html
{% extends "layout.html" %}
{% block body %}
<h3>Hakkımda</h3>
<hr>
<p>Burcum ipsum dolor sit amet consectetur adipisicing elit. Expedita, nam asperiores! Reiciendis nostrum accusantium alias aut laborum sed dignissimos cupiditate a eveniet commodi! Perferendis vel tenetur modi aperiam praesentium, culpa debitis dicta, dignissimos repellendus provident quaerat ex tempora nostrum veniam beatae ipsa aspernatur laudantium, minus doloremque assumenda necessitatibus optio totam. Enim molestias itaque doloribus tenetur dolor odio earum nam alias rem. Ut exercitationem sequi ea obcaecati dicta voluptatum molestiae fugit, minus ab harum illo maxime quo aliquid, officia maiores saepe, aspernatur tempore! Consequuntur amet incidunt, vero officia recusandae voluptatem molestias nostrum vel corrupti dolorem facere pariatur similique reprehenderit quaerat fugit porro et perferendis quia deserunt consequatur molestiae culpa expedita id? Dolore temporibus veritatis maiores ad obcaecati accusantium earum architecto, consectetur laborum quaerat illo praesentium placeat qui laudantium voluptatem tenetur perferendis ea labore officia, neque, minima dolorem explicabo aliquid animi. Enim quidem natus architecto animi dolor beatae saepe voluptas vitae ut?</p>
{% endblock body %}<h3>Hakkımda</h3>
<hr>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita, nam asperiores! Reiciendis nostrum accusantium alias aut laborum sed dignissimos cupiditate a eveniet commodi! Perferendis vel tenetur modi aperiam praesentium, culpa debitis dicta, dignissimos repellendus provident quaerat ex tempora nostrum veniam beatae ipsa aspernatur laudantium, minus doloremque assumenda necessitatibus optio totam. Enim molestias itaque doloribus tenetur dolor odio earum nam alias rem. Ut exercitationem sequi ea obcaecati dicta voluptatum molestiae fugit, minus ab harum illo maxime quo aliquid, officia maiores saepe, aspernatur tempore! Consequuntur amet incidunt, vero officia recusandae voluptatem molestias nostrum vel corrupti dolorem facere pariatur similique reprehenderit quaerat fugit porro et perferendis quia deserunt consequatur molestiae culpa expedita id? Dolore temporibus veritatis maiores ad obcaecati accusantium earum architecto, consectetur laborum quaerat illo praesentium placeat qui laudantium voluptatem tenetur perferendis ea labore officia, neque, minima dolorem explicabo aliquid animi. Enim quidem natus architecto animi dolor beatae saepe voluptas vitae ut?</p>

templates/addarticle.html
{% extends "layout.html" %}
{% block style %}

{% endblock style %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h3>Blog Yazısı</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- ckeditor dahil etmek için form.media-->
            {{form.media}}
            {{form | crispy}}
            <button type="submit" class="btn btn-danger btn-block ">Gönder</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
    <div class="col-sm-8 offset-sm-2"> 
        <h3 class="text-center">Yazılar</h3>
        <hr>
        <form class="text-right">
                {% csrf_token %}
                <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Başlıklarda Ara...">
                <button type="submit" class="btn btn-secondary btn">Ara</button>
        </form>
        {% if articles %}
            {% for article in articles %}
                <!-- detail.html den koypayalandı -->

                <!-- Post Content Column -->
                <!-- Title -->
                <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
                <!-- Author -->
                <p class="lead">
                <a href="{% url 'about' %}" class=" font-weight-bold font-italic"> <small>{{article.author.first_name}} {{article.author.last_name}}</small></a><small> tarafından yazıldı.</small>
                </p>
                <hr>
                <!-- Date/Time -->
                <p> {{article.created_date}} </p>
                <hr>
                <!-- Preview Image -->
                {% if article.article_image %}
                    <a href="{% url 'article:detail' article.id %}"> <img class="img-fluid rounded" src=" {{article.article_image.url}} " alt=""> </a>
                {% endif %}
            
                <hr>
                <!-- Post Content -->
                <p class="lead"> {{article.content | safe | truncatewords:30}} </p>
                <hr> 
                <span class="d-flex justify-content-end" ><a href="{%url 'article:detail' article.id %}" class="btn btn-secondary">Devamını oku...</a></span>
                <!-- Düğmeyi sağa dayamanın bir diğer yolu da float:right"-->
            {% comment %}  <a style="float: right" href="/articles/article/{{article.id}}" class="btn btn-secondary text-right">Devamını oku...</a> {% endcomment %}
            {% endfor %}
        {% else %}
            <!--Arama işleminden sonra herhangi bir yazı bululanamzsa-->
            <div class="alert alert-danger mt-3 pt-4">
                <p>Eşleşen bir başlık bulunamadı!</p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}
{% block body %}
    <h3>Kontrol Panalei</h3>
    <hr>
    <p>
        Hoşgeldin, {{request.user.first_name}}
    </p>
    <hr>
    <a href="{% url 'article:addarticle' %}" class="btn btn-danger">Yazı Yaz</a>
        {% if articles %}
        <!--bootstrap table hover örneği baz alındı-->
        <table class="table table-bordered table-secondary table-hover mt-4">
            <thead>
                <tr>
                <th scope="col">id</th>
                <th class="text-center" scope="col">Başlık</th>
                <th class="text-center" scope="col">Yazar</th>
                <th class="text-center" scope="col">Tarih</th>
                <th class="text-center" scope="col">Güncelle</th>
                <th class="text-center" scope="col">Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr class="table-light">
                        <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                        <td>{{article.author}}</td>
                        <td>{{article.created_date}}</td>
                        <td class="text-center"><a class="btn btn-danger" href="{% url 'article:update' article.id %}">Güncelle</a></td>
                        <td class="text-center"><a class="btn btn-danger" data-toggle="modal" data-target="#silmodal">Sil</a></td>
                        <!-- MODAL -->
                        <div class="modal fade" id="silmodal" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-center">Sil</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>{{article.title}} isimli yazıyı silmeyi onaylıyor musunuz?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">HAYIR</button>
                                <a class="btn btn-danger" href="{% url 'article:delete' article.id %}">EVET</a>
                            </div>
                            </div>
                        </div>
                    </div>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
    <div class="alert alert-danger mt-3">
        <p>Henüz blog yazınız bulunmuyor!</p>
        <p> {{ result }}</p>
    </div>
    {% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{%load static%}
{% block body %}
    <!-- https://startbootstrap.github.io/startbootstrap-blog-post/ adresinden alındı -->
    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{article.title}}</h1>

        <!-- Author -->
        <p class="lead">
        <a href="{% url 'about' %}" class=" font-weight-bold font-italic"> <small>{{article.author.first_name}} {{article.author.last_name}}</small></a><small> tarafından yazıldı.</small>
        </p>
        <hr>
        <!-- Date/Time -->
        <p> {{article.created_date}} </p>
        <hr>
        <!-- Preview Image -->
        {% if article.article_image %}
          <img class="img-fluid rounded" src=" {{article.article_image.url}} " alt=""> 
        {% endif %}
     
        <hr>
        <!-- Post Content -->
        <p class="lead"> {{article.content | safe}} </p>        
        <hr>
        {% if comments %}
        
        {% else %}
          <div class="alert alert-danger">
            <p>Henüz yorum yapılmamış! İlk yorum yazan siz olun!</p>
          </div>
        {% endif %}

        <!-- Comments Form -->
        <div class="card col-lg ">
          <h5 class="card-header">Yorum ekle:</h5>
          <div id = "form-return" class="card-body">
            <form action="{% url 'article:comment' article.id %}" method = "post">
              {% csrf_token %}
              <div class="form-group">
                <label for="formGroupName">İsminiz:</label>
                <input type="text" name = "comment_author" class="form-control" id="formGroupName" required placeholder="İsminiz...">
              </div>
              <div class="form-group">
                <label for="formGroupEmail">E-posta Adresiniz:</label>
                <input type="email" name = "comment_email" class="form-control" id="formGroupEmail" required placeholder="ornek@ornek.com">
              </div>
              <div class="form-group">
                 <label for="formGroupComment">Yorumunuz:</label>
                <textarea id="formGroupComment" name = "comment_content" class="form-control" required rows="7"></textarea>
              </div>
              <button for = "form-return" type="submit" class="btn btn-danger">Gönder</button>
            </form>
          </div>
        </div>
        <!-- comment end -->
        <hr>
        <h4>Yorumlar</h4>
        <hr>
        <!-- comments -->
        {% if comments %}
          {% for comment in comments  %}
          <div class="media">
          <img class="d-flex mr-3 " src="{% static 'icons/chat-right-text-fill.svg'%}" width=50 height=50 alt="comment avatar">
          <div class="jumbotron media-body p-3">
            <h5 class="text-primary">{{comment.comment_author}} <span class= "text-dark"><small><ins> tarafından {{comment.comment_date}} tarihinde yazıldı.</ins></small></span></h5>
            {{comment.comment_content | safe}}
          </div>
        </div>
          {% endfor %}
        {% else %}
        {% endif %}
      </div>
      <!-- Post conent end -->
    </div>
    <!-- /.row -->


{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}
    <div class="jumbotron text-center">
        <h3>Sayfama Hoşgeldiniz!</h3>
        <p>Burada sizlerle deneyimlerimi, fikirlerimi paylaşıyorum.<br>Keyifli okumalar...</p>
    </div>   
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- Bootstrap static css dosyası -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% block style %}
       
    {% endblock style %}
    <title>CE BLOG</title>
</head>
<body>
{% include "includes/navbar.html" %}
    <main class="container mt-4 mb-5">
        <div class="mt-5 pt-5">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div id="messages" class="alert alert-danger text-center">
                        <strong>{{ message }}</strong>
                    </div>                
                {% else %}
                    <div id="messages" class="alert alert-{{ message.tags }} text-center">
                        <strong>{{ message }}</strong>
                    </div>                    
                {% endif %}                   
            {% endfor %}
        {% endif %}        
        {% block body %}

        {% endblock body %}
        </div>    
    </main>
    {% block script %}
        <!-- Django mesajlarını belirli süre sonra temizleyen script-->
        <script type="text/javascript">window.setTimeout("document.getElementById('messages').style.display='none';", 3500); </script>
        <!-- Bootstrap gereksinimi static scriptler -->
        <script src="{% static 'js/jquery-3.5.1.js'%} "></script>
        <script src="{% static 'js/bootstrap.bundle.js'%} "></script>
        <script src="{% static 'js/run_prettify.js'%}"></script>
    {% endblock script %}   
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <h3 class="text-center">Giriş Yap</h3>
        <hr>
        <form class="text-center" method="post">
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-danger btn-block ">Giriş</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/logout.html
{% extends "layout.html" %}
{% block body %}
<h3>Çıkış Yap</h3>
<hr>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}
    <div class="col-sm-8 offset-sm-2">
        <h3 class="text-center">Kayıt Ol</h3>
        <hr>
        <form class="text-center" method="post">
            {% csrf_token %}
            {{form | crispy}}
            <button type="submit" class="btn btn-danger btn-block ">Kayıt</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/update.html
<!-- addarticle.html den kopyalandı-->
{% extends "layout.html" %}
{% block style %}

{% endblock style %}
{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h3>Blog Yazısı</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- ckeditor dahil etmek için form.media-->
            {{form.media}}
            {{form | crispy}}
            <button type="submit" class="btn btn-danger btn-block ">Güncelle</button>
        </form>
    </div>
</div>
{% endblock body %}